{
 "title": "k8s-network-probe",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "func", "query": "http,tcp,ping,dns" },
   {
    "name": "target",
    "query": {
     "query": "label_values(network_probe_probe_result{func=\"$func\"},target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "探针部署情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"k8s-network-probe\",pod=~\"k8s-network-probe-agent.*\"}"
    }
   ]
  },
  {
   "title": "探测目标详情",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "network_probe_server_targets", "legendFormat": "{{func}}" }
   ]
  },
  {
   "title": "探测目标成功率",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(func)(network_probe_server_targets)",
     "legendFormat": "{{func}}"
    }
   ]
  },
  {
   "title": "探测失败原因统计",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(err_reason)(network_probe_probe_result==-1)",
     "legendFormat": "{{err_reason}}"
    }
   ]
  },
  {
   "title": "探测成功百分比",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(network_probe_probe_result==-1)",
     "legendFormat": "失败的"
    },
    {
     "expr": "count(network_probe_probe_result==1)",
     "legendFormat": "成功的"
    }
   ]
  },
  {
   "title": "探测失败项",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "network_probe_probe_result==-1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "【探测结果】【探针类型：${func}】 【目标:${target}】",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_probe_probe_result{func=\"${func}\",target=\"${target}\"}",
     "legendFormat": "探针节点: {{probe_node}} | 探针ip {{probe_ip}} | 错误原因: {{err_reason}}"
    }
   ]
  },
  {
   "title": "【探测耗时】【探针类型：${func}】 【目标:${target}】",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "network_probe_duration_seconds{func=\"${func}\",target=\"${target}\"}",
     "legendFormat": "探针节点: {{probe_node}} | 探针ip {{probe_ip}} "
    }
   ]
  }
 ]
}